### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Saqibi4213**
##This Is Simple Palindrome Checker Project 
#Using 
- Html
- Css
- Java-script 
and the project is responsive 
please review my project  and if their is anything I remove or Add 
please review my project @Nooria150 @iamfarhatsharefi 
Sir 
Thank YOU !

### CODE REVIEW

**Review by Nooria150 — APPROVED** [review]
I checked your project. everything was perfect from my view of point.

**Comment by Nooria150** [comment]
@Saqibi4213 
I checked your project. everything was perfect from my view of point.
otherwise farhat sharifi will also check it.

**Comment by iamfarhatsharefi** [comment]
@Saqibi4213 
Great Design Implemented
✔ Created a professional Repo (You created a repository with your project name)
✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔ Commit messages are meaningful
✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔ No linter errors (All linters checks have been passed 🟢)
✔ You have followed the Palindrome checker project task and committed using the command line
✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔Your code is clean
✔Your repo has a professional README.md file

**Review by ahzamir — CHANGES_REQUESTED** [review]
@Saqibi4213 

- Well done by implementing lots of requirements but still your code misses these requirements:

When you click on the #check-btn element without entering a value into the #text-input element, an alert should appear with the text "Please input a value".

**Comment by Saqibi4213** [comment]
Hello sir @ahzamir i solved the alert error in j.s code please re-review my project 
Thank You !

**Comment by Saqibi4213** [comment]
> Hello sir @ahzamir i solved the alert error in j.s code please re-review my project Thank You !

Sir @ahzamir  i waited for days can u please check my pull request

**Comment by ahzamir** [comment]
@Saqibi4213 

- Well done by implementing the requested changes, but your project has one more issue its design is not responsive for the mobile version please make it responsive.

**Comment by Saqibi4213** [comment]
> @Saqibi4213
> 
> * Well done by implementing the requested changes, but your project has one more issue its design is not responsive for the mobile version please make it responsive.



> @Saqibi4213
> 
> * Well done by implementing the requested changes, but your project has one more issue its design is not responsive for the mobile version please make it responsive.

**Comment by Saqibi4213** [comment]
> @Saqibi4213
> 
> * Well done by implementing the requested changes, but your project has one more issue its design is not responsive for the mobile version please make it responsive.



Hello Sir @ahzamir  can you please check my pull all errors and requirements are solved

**Review by ahzamir — APPROVED** [review]
### Hi @Saqibi4213 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF (2)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Palindrome Checker project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your repo has a professional README.md file
✔️Your code is clean
✔️Your design is impressive and responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
